### numpy array creation


In [3]:
import numpy as np

In [5]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

### 2d array

In [7]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

### zero array


In [9]:
zarr=np.zeros((3,4))
zarr


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### one array


In [10]:
oarr=np.ones((3,4))
oarr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### range arrey

In [12]:
rarr=np.arange(1,10,2)
rarr

array([1, 3, 5, 7, 9])

### line space

In [13]:
ls=np.linspace(0,1,5)
ls

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### identity metrix

In [14]:
im=np.eye(4)
im

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### random array

In [15]:
ra=np.random.rand(3,3)
ra

array([[0.09518203, 0.89403135, 0.85548507],
       [0.94599014, 0.44287027, 0.01481767],
       [0.02313375, 0.30471113, 0.08918274]])

### array properties

In [16]:
arr1.shape,arr1.dtype,arr1.ndim

((5,), dtype('int64'), 1)

In [17]:
np.random.rand(2,3)

array([[0.49912945, 0.50134106, 0.43326037],
       [0.80960535, 0.73456698, 0.09694352]])

In [18]:
np.random.randn(2,3)

array([[ 0.59219866,  0.06427254, -0.73759548],
       [-0.6563935 , -0.10369906, -0.24885046]])

In [19]:
np.random.randint(1,10,(2,3))

array([[6, 5, 2],
       [6, 1, 7]], dtype=int32)

In [20]:
m=[1,2,3,4,5]
np.zeros_like(m)

array([0, 0, 0, 0, 0])

In [21]:
np.ones_like(m)

array([1, 1, 1, 1, 1])