## numpy array indexing

In [2]:
import numpy as np

### 1d array indexing

In [3]:
arr=np.array([1,2,3,4,5])
arr[2]

np.int64(3)

### 1d array slicing

In [5]:
arr[1:2]

array([2])

In [7]:
arr[:3]

array([1, 2, 3])

In [8]:
arr[2:]

array([3, 4, 5])

In [9]:
arr[::2]

array([1, 3, 5])

### 2d array slicing

In [13]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [11]:
arr2[:,1]

array([2, 5, 8])

In [12]:
arr2[1,:]

array([4, 5, 6])

### 2d indexing

In [15]:
arr2[0,0]

np.int64(1)

In [16]:
arr2[1,2]

np.int64(6)

In [17]:
arr2[-1,-1]


np.int64(9)

### boolean indexing

In [18]:
arr=np.array([5,10,15,20,25])
arr[arr>15]

array([20, 25])

### fancy indexing

In [20]:
a=np.array([100,200,300,400])
a[[0,2]]

array([100, 300])

### modify values using indexing

In [21]:
arr=np.array([1,2,3,4])
arr[1]=20
arr

array([ 1, 20,  3,  4])