In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [3]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[4:])

[5 6 7 8]


In [4]:
arr=np.array([1,2,3,4,5,6,7,8])
arr[-3:-1]

array([6, 7])

In [5]:
arr=np.array([1,2,3,4,5,6,7,8])
arr[1:2:4]

array([2])

In [6]:
arr=np.array([1,2,3,4,5,6,7,8])
arr[::4]

array([1, 5])

In [8]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,0:4])

[6 7 8 9]


In [9]:
arr=np.array([[1,2,3,4],[5,7,10,8]])
print(arr[0:3,2])

[ 3 10]


In [10]:
arr=np.array([[1,2,3,4],[5,7,10,8]])
print(arr[0:2,1:4])

[[ 2  3  4]
 [ 7 10  8]]


In [11]:
arr=np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [13]:
arr=np.array([1,2,3,4],dtype='S')
arr

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [17]:
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32
