In [1]:
import numpy as np

In [2]:
array=np.array ([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
n=array.size
reshaped1=array.reshape((4,4))
reshaped2=np.reshape(array,(2,8))
print(reshaped1)
print(reshaped2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [3]:
array=np.array ([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
reshaped=array.reshape(2,2,4)
reshaped

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [4]:
gf=np.array([1,2,3,4,5,6])
gf.resize(2,3)
gf

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
gf=np.array([1,2,3,4,7,6,5])
gf.resize(3,4)
gf

ValueError: cannot resize an array that may be referenced by another object.
It is possible that this is a false positive.
If you are sure that the array is uniquely referenced, set refcheck=False.