In [1]:
import numpy as np

In [3]:
a= np.array([5,72,13,100])
b= np.array([2,5,10,30])
s=np.add(a,b)
s


array([  7,  77,  23, 130])

In [4]:
a= np.array([5,72,13,100])
b= np.array([2,5,10,30])
s=np.subtract(a,b)
s

array([ 3, 67,  3, 70])

In [5]:
a= np.array([5,72,13,100])
b= np.array([2,5,10,30])
mul=np.multiply(a,b)
mul

array([  10,  360,  130, 3000])

In [6]:
a= np.array([5,72,13,100])
b= np.array([2,5,10,30])
div=np.divide(a,b)
div


array([ 2.5       , 14.4       ,  1.3       ,  3.33333333])

In [7]:
a= np.array([5,3,10,8])
b= np.array([2,3,2,4])
pow=np.power(a,b)
pow

array([  25,   27,  100, 4096])

In [8]:
a= np.array([5,19,106,8])
b= np.array([2,4,9,5])
mod=np.mod(a,b)
mod

array([1, 3, 7, 3])

In [10]:
arr=[20,2,.2,10.4]
print(" Sum of the arr:",np.sum(arr))
s=np.sum(arr)
print(np.sum(arr,dtype=np.uint8))
print(np.sum(arr,dtype=np.float32))
print(np.sum(arr).dtype==np.uint)
print(np.sum(arr).dtype==np.float64)
s.dtype

 Sum of the arr: 32.6
32
32.6
False
True


dtype('float64')

In [ ]:
arr=[[14,17,12,33,44],[15,6,27,8,17],[23,2,54,1,4]]
print("n Sum of arr:",np.sum(arr))
print(np.sum(arr,axis=0))
# axis=0 means it takes the sum of the elements in coloumn eg:here it takes the sum of 14+15+23=5
print(np.sum(arr,axis=1))
# axis=1 means it takes the sum of the elements in row eg:here it takes the sum of 14 +17+12+33+44=120
print(np.sum(arr,axis=0,keepdims=True))