In [2]:
import numpy as np

In [3]:
a=np.array([[2,4],[6,8]])

In [5]:
b=np.array([[1,3],[5,7]])

In [6]:
a+b

array([[ 3,  7],
       [11, 15]])

In [7]:
a-b

array([[1, 1],
       [1, 1]])

In [8]:
a*b

array([[ 2, 12],
       [30, 56]])

In [11]:
np.matmul(a,b)

array([[22, 34],
       [46, 74]])

In [14]:
a.T

array([[2, 6],
       [4, 8]])

In [15]:
np.linalg.det(a)

np.float64(-8.000000000000002)

In [16]:
np.linalg.inv(a)

array([[-1.  ,  0.5 ],
       [ 0.75, -0.25]])

In [19]:
sale=np.array([[120,150,170,200],
                [130,160,180,220],
                [140,170,190,240],
                [150,180,200,260]])

In [20]:
sale.sum(axis=1)

array([640, 690, 740, 790])

In [21]:
sale.sum(axis=0)

array([540, 660, 740, 920])

In [22]:
sale.max()

np.int64(260)

In [23]:
sale.min()

np.int64(120)

In [24]:
sale.mean()

np.float64(178.75)

In [25]:
np.argmax(sale.sum(axis=1))+1

np.int64(4)

In [26]:
np.argmax(sale.sum(axis=0))+1

np.int64(4)

In [27]:
sale.sum()

np.int64(2860)

In [28]:
sale*1.10

array([[132., 165., 187., 220.],
       [143., 176., 198., 242.],
       [154., 187., 209., 264.],
       [165., 198., 220., 286.]])

In [ ]:
sale>180