In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d.flatten()


array([1, 2, 3, 4, 5, 6])

In [4]:
arr2d.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [6]:
np.vstack((a, b))
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [7]:
arr = np.array([10, 20, 30, 40, 50, 60])
np.split(arr, 3)

[array([10, 20]), array([30, 40]), array([50, 60])]

In [8]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

r=np.vsplit(arr, 3)
r=np.hsplit(arr, 3)
r

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [9]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.append(arr, [70, 80])