In [13]:
import numpy as np

In [4]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [5]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [6]:
arr.shape

(3, 3)

In [7]:
arr.size

9

In [8]:
arr.ndim

2

In [9]:
arr.dtype

dtype('int64')

In [10]:
arr=np.arange(1,25)
arr.reshape(4,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [12]:
arr.reshape(2,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [14]:
arr=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34],[41,42,43,44]])
arr

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [15]:
arr[1,2]

np.int64(23)

In [16]:
arr[2]

array([31, 32, 33, 34])

In [17]:
arr[:,1]

array([12, 22, 32, 42])

In [18]:
arr[-1]

array([41, 42, 43, 44])

In [19]:
arr[:,-1]

array([14, 24, 34, 44])

In [29]:
a=np.array([6,7,8,9,10])
b=np.array([1,2,3,4,5])
a+b

array([ 7,  9, 11, 13, 15])

In [30]:
a-b

array([5, 5, 5, 5, 5])

In [31]:
a*b

array([ 6, 14, 24, 36, 50])

In [32]:
a/b

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [34]:
a**2

array([ 36,  49,  64,  81, 100])

In [35]:
b**3

array([  1,   8,  27,  64, 125])

In [36]:
mark=np.array([55,67,89,90,78,95,45,82,60,74])
np.max(mark)

np.int64(95)

In [37]:
np.min(mark)

np.int64(45)

In [38]:
np.mean(mark)

np.float64(73.5)

In [40]:
np.median(mark)

np.float64(76.0)

In [41]:
np.std(mark)

np.float64(15.64129150677782)

In [42]:
np.sum(mark)

np.int64(735)

In [43]:
np.average(mark)

np.float64(73.5)

In [44]:
np.sum(mark)

np.int64(735)

In [45]:
salary=np.array([25000,40000,18000,55000,62000,28000,72000])
salary>30000

array([False,  True, False,  True,  True, False,  True])

In [46]:
salary<30000

array([ True, False,  True, False, False,  True, False])

In [47]:
(salary>=30000)&(salary<=60000)

array([False,  True, False,  True, False, False, False])

In [48]:
np.sum(salary>50000)

np.int64(3)

In [50]:
randm=np.random.randint(1,101,10)
randm

array([19, 66, 14, 37, 26, 28, 56,  9, 43, 71], dtype=int32)

In [51]:
randm=np.random.randint(10,51,(4,4))
randm

array([[49, 38, 18, 23],
       [15, 32, 24, 10],
       [10, 18, 18, 28],
       [28, 46, 33, 43]], dtype=int32)

In [52]:
np.max(randm)

np.int32(49)

In [53]:
np.min(randm)

np.int32(10)

In [54]:
np.mean(randm)

np.float64(27.0625)

In [55]:
a=np.array([[2,5],[5,8]])
b=np.array([[1,3],[6,7]])
a+b

array([[ 3,  8],
       [11, 15]])

In [56]:
a-b

array([[ 1,  2],
       [-1,  1]])

In [57]:
a*b

array([[ 2, 15],
       [30, 56]])

In [58]:
np.matmul(a,b)

array([[32, 41],
       [53, 71]])

In [60]:
a.T

array([[2, 5],
       [5, 8]])

In [61]:
np.linalg.det(a)

np.float64(-8.999999999999998)

In [62]:
np.linalg.inv(a)

array([[-0.88888889,  0.55555556],
       [ 0.55555556, -0.22222222]])